Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,68 +22,68 @@ on:
 
 jobs:
   # 同步上游分支
-  SyncFork:
-    name: SyncFork
+  # SyncFork:
+  #   name: SyncFork
 
     # 在最新版的Ubuntu系统上运行
     runs-on: ubuntu-latest
 
     # 定义SyncFork的变量
-    outputs:
-      MAIN_YML_FILES_INCONSISTENT: ${{ steps.compare_main_yml_files.outputs.MAIN_YML_FILES_INCONSISTENT }}
+    # outputs:
+    #   MAIN_YML_FILES_INCONSISTENT: ${{ steps.compare_main_yml_files.outputs.MAIN_YML_FILES_INCONSISTENT }}
 
-    steps:
-      # 使用GitHub Actions提供的动作来检出代码库
-      - name: Checkout Repository
-        uses: actions/checkout@main
+    # steps:
+    #   # 使用GitHub Actions提供的动作来检出代码库
+    #   - name: Checkout Repository
+    #     uses: actions/checkout@main
 
-      - name: Configure Git
-        run: |
-          # 配置Git用户信息
-          git config --global user.email "actions@github.com"
-          git config --global user.name "GitHub Actions"
+    #   - name: Configure Git
+    #     run: |
+    #       # 配置Git用户信息
+    #       git config --global user.email "actions@github.com"
+    #       git config --global user.name "GitHub Actions"
 
-      - name: Fetch upstream changes
-        run: |
-          # 添加上游仓库作为远程仓库，并获取上游仓库的main分支的最新更改
-          REPO_NAME="NianBroken/ZFCheckScores"
-          REPO_URL="https://github.com/$REPO_NAME.git"
-          echo "Repo Url: $REPO_URL"
-          git remote add upstream "$REPO_URL"
-          git fetch upstream main
+    #   - name: Fetch upstream changes
+    #     run: |
+    #       # 添加上游仓库作为远程仓库，并获取上游仓库的main分支的最新更改
+    #       REPO_NAME="NianBroken/ZFCheckScores"
+    #       REPO_URL="https://github.com/$REPO_NAME.git"
+    #       echo "Repo Url: $REPO_URL"
+    #       git remote add upstream "$REPO_URL"
+    #       git fetch upstream main
 
-      - name: Compare main.yml files
-        id: compare_main_yml_files
-        run: |
-          tree -L 3 --dirsfirst
-          # 比对当前分支的main.yml文件与上游分支的main.yml文件是否一致
-          if cmp -s .github/workflows/main.yml <(git show upstream/main:.github/workflows/main.yml); then
-            echo "MAIN_YML_FILES_INCONSISTENT=False" >> $GITHUB_OUTPUT
-            echo "main.yml file is consistent"
-          else
-            echo "MAIN_YML_FILES_INCONSISTENT=True" >> $GITHUB_OUTPUT
-            echo "main.yml file is inconsistent"
-            echo "::error title=main.yml file is inconsistent!" \
-            "::The content of the 'main.yml' file in the current branch" \
-            "does not match the content of the 'main.yml' file in the" \
-            "upstream branch! You need to synchronize the upstream branch" \
-            "manually! If you don't synchronize, there is a chance that" \
-            "your code will have an uncontrollable fatal bug!"
-          fi
+    #   - name: Compare main.yml files
+    #     id: compare_main_yml_files
+    #     run: |
+    #       tree -L 3 --dirsfirst
+    #       # 比对当前分支的main.yml文件与上游分支的main.yml文件是否一致
+    #       if cmp -s .github/workflows/main.yml <(git show upstream/main:.github/workflows/main.yml); then
+    #         echo "MAIN_YML_FILES_INCONSISTENT=False" >> $GITHUB_OUTPUT
+    #         echo "main.yml file is consistent"
+    #       else
+    #         echo "MAIN_YML_FILES_INCONSISTENT=True" >> $GITHUB_OUTPUT
+    #         echo "main.yml file is inconsistent"
+    #         echo "::error title=main.yml file is inconsistent!" \
+    #         "::The content of the 'main.yml' file in the current branch" \
+    #         "does not match the content of the 'main.yml' file in the" \
+    #         "upstream branch! You need to synchronize the upstream branch" \
+    #         "manually! If you don't synchronize, there is a chance that" \
+    #         "your code will have an uncontrollable fatal bug!"
+    #       fi
 
-      - name: Force push changes to main branch
-        run: |
-          # 将更改强制推送到main分支
-          git add .
-          git commit -m "Update branch" || true
-          git push origin main --force
+    #   - name: Force push changes to main branch
+    #     run: |
+    #       # 将更改强制推送到main分支
+    #       git add .
+    #       git commit -m "Update branch" || true
+    #       git push origin main --force
 
-  # 检查成绩
-  CheckScores:
-    name: CheckScores
+  # 检查通知
+  Check:
+    name: Check
 
     # SyncFork执行完成后运行
-    needs: SyncFork
+    # needs: SyncFork
 
     # 在最新版的Ubuntu系统上运行
     runs-on: ubuntu-latest
@@ -113,8 +113,7 @@ jobs:
           FORCE_PUSH_MESSAGE: ${{ github.event.inputs.force_push_message }}
           MAIN_YML_FILES_INCONSISTENT: ${{ needs.SyncFork.outputs.MAIN_YML_FILES_INCONSISTENT }}
           URL: ${{ secrets.URL }}
-          USERNAME: ${{ secrets.USERNAME }}
-          PASSWORD: ${{ secrets.PASSWORD }}
+          COOIKES: ${{ secrets.COOKIES }}
           TOKEN: ${{ secrets.TOKEN }}
           GITHUB_EVENT_NAME: ${{ github.event_name }}
           GITHUB_TRIGGERING_ACTOR: ${{ github.triggering_actor }}
